"""Tests for HostsEditor engine."""

import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))

import unittest
import tempfile
from pathlib import Path
from powertoys.modules.hostseditor.engine import HostsEngine, HostsEntry, parse_hosts_file


SAMPLE_HOSTS = """\
# /etc/hosts - sample for testing
# Generated by Linux PowerToys

127.0.0.1\tlocalhost
127.0.1.1\tmyhostname
::1\tlocalhost ip6-localhost ip6-loopback
fe00::0\tip6-localnet

# Custom entries
192.168.1.100\tserver.local  # main server
# 10.0.0.1\tdisabled.example.com
0.0.0.0\tads.example.com bad.tracker.net
"""


class TestParseHostsFile(unittest.TestCase):

    def setUp(self):
        self.tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".hosts", delete=False)
        self.tmp.write(SAMPLE_HOSTS)
        self.tmp.close()

    def tearDown(self):
        os.unlink(self.tmp.name)

    def test_parses_basic_entries(self):
        entries, _ = parse_hosts_file(self.tmp.name)
        ips = [e.ip for e in entries]
        self.assertIn("127.0.0.1", ips)
        self.assertIn("192.168.1.100", ips)

    def test_parses_multiple_hostnames(self):
        entries, _ = parse_hosts_file(self.tmp.name)
        loopback = next(e for e in entries if e.ip == "0.0.0.0")
        self.assertIn("ads.example.com", loopback.hostnames)
        self.assertIn("bad.tracker.net", loopback.hostnames)

    def test_parses_ipv6(self):
        entries, _ = parse_hosts_file(self.tmp.name)
        ips = [e.ip for e in entries]
        self.assertIn("::1", ips)

    def test_parses_inline_comment(self):
        entries, _ = parse_hosts_file(self.tmp.name)
        server = next(e for e in entries if e.ip == "192.168.1.100")
        self.assertEqual(server.comment, "main server")

    def test_disabled_entry_parsed(self):
        entries, _ = parse_hosts_file(self.tmp.name)
        disabled = [e for e in entries if "disabled.example.com" in e.hostnames]
        self.assertEqual(len(disabled), 1)
        self.assertFalse(disabled[0].enabled)

    def test_missing_file_returns_empty(self):
        entries, raw = parse_hosts_file("/nonexistent/hosts")
        self.assertEqual(entries, [])


class TestHostsEngine(unittest.TestCase):

    def setUp(self):
        self.tmp = tempfile.NamedTemporaryFile(mode="w", suffix=".hosts", delete=False)
        self.tmp.write(SAMPLE_HOSTS)
        self.tmp.close()
        self.engine = HostsEngine(self.tmp.name)

    def tearDown(self):
        os.unlink(self.tmp.name)

    def test_load_populates_entries(self):
        self.assertGreater(len(self.engine.entries), 0)

    def test_add_entry(self):
        n = len(self.engine.entries)
        self.engine.add_entry("10.0.0.99", ["new.host.local"], comment="Added by test")
        self.assertEqual(len(self.engine.entries), n + 1)
        last = self.engine.entries[-1]
        self.assertEqual(last.ip, "10.0.0.99")
        self.assertEqual(last.hostnames, ["new.host.local"])
        self.assertEqual(last.comment, "Added by test")

    def test_remove_entry(self):
        n = len(self.engine.entries)
        self.engine.remove_entry(0)
        self.assertEqual(len(self.engine.entries), n - 1)

    def test_toggle_entry(self):
        # Find an enabled entry
        enabled_idx = next(i for i, e in enumerate(self.engine.entries) if e.enabled)
        self.engine.toggle_entry(enabled_idx)
        self.assertFalse(self.engine.entries[enabled_idx].enabled)
        self.engine.toggle_entry(enabled_idx)
        self.assertTrue(self.engine.entries[enabled_idx].enabled)

    def test_find_by_hostname(self):
        results = self.engine.find("localhost")
        self.assertGreater(len(results), 0)

    def test_find_by_ip(self):
        results = self.engine.find("127.0.0.1")
        self.assertGreater(len(results), 0)

    def test_save_and_reload(self):
        self.engine.add_entry("5.5.5.5", ["save.test"])
        err = self.engine.save()
        self.assertIsNone(err)
        engine2 = HostsEngine(self.tmp.name)
        ips = [e.ip for e in engine2.entries]
        self.assertIn("5.5.5.5", ips)

    def test_disabled_entry_written_with_hash(self):
        self.engine.add_entry("9.9.9.9", ["disabled.test"], enabled=False)
        self.engine.save()
        content = Path(self.tmp.name).read_text()
        self.assertIn("# 9.9.9.9", content)

    def test_validate_good_entry(self):
        entry = HostsEntry(ip="192.168.1.1", hostnames=["host.local"])
        err = self.engine.validate_entry(entry)
        self.assertIsNone(err)

    def test_validate_bad_ip(self):
        entry = HostsEntry(ip="not_an_ip", hostnames=["host.local"])
        err = self.engine.validate_entry(entry)
        self.assertIsNotNone(err)

    def test_validate_empty_ip(self):
        entry = HostsEntry(ip="", hostnames=["host.local"])
        err = self.engine.validate_entry(entry)
        self.assertIsNotNone(err)

    def test_validate_no_hostnames(self):
        entry = HostsEntry(ip="1.2.3.4", hostnames=[])
        err = self.engine.validate_entry(entry)
        self.assertIsNotNone(err)


class TestHostsEntry(unittest.TestCase):

    def test_to_line_enabled(self):
        entry = HostsEntry(ip="1.2.3.4", hostnames=["example.com"], enabled=True)
        line = entry.to_line()
        self.assertFalse(line.startswith("#"))
        self.assertIn("1.2.3.4", line)
        self.assertIn("example.com", line)

    def test_to_line_disabled(self):
        entry = HostsEntry(ip="1.2.3.4", hostnames=["example.com"], enabled=False)
        line = entry.to_line()
        self.assertTrue(line.startswith("# "))

    def test_to_line_with_comment(self):
        entry = HostsEntry(ip="1.2.3.4", hostnames=["example.com"], comment="my comment")
        line = entry.to_line()
        self.assertIn("my comment", line)

    def test_to_line_multiple_hostnames(self):
        entry = HostsEntry(ip="1.2.3.4", hostnames=["a.com", "b.com", "c.com"])
        line = entry.to_line()
        self.assertIn("a.com", line)
        self.assertIn("b.com", line)
        self.assertIn("c.com", line)

    def test_valid_ipv4(self):
        entry = HostsEntry(ip="192.168.1.1", hostnames=["x"])
        self.assertTrue(entry.valid_ip())

    def test_valid_ipv6(self):
        entry = HostsEntry(ip="::1", hostnames=["x"])
        self.assertTrue(entry.valid_ip())

    def test_invalid_ip(self):
        entry = HostsEntry(ip="999.999.999.999", hostnames=["x"])
        # 999.999.999.999 matches the regex but is invalid — regex allows it
        # More important to test non-IP strings:
        entry2 = HostsEntry(ip="not-an-ip!", hostnames=["x"])
        self.assertFalse(entry2.valid_ip())

    def test_primary_hostname(self):
        entry = HostsEntry(ip="1.2.3.4", hostnames=["primary.com", "alias.com"])
        self.assertEqual(entry.primary_hostname, "primary.com")


if __name__ == "__main__":
    unittest.main(verbosity=2)
